language: csharp
sudo: required
env:
  global:
    - NUODB_HOME=/opt/nuodb
    - NUO_ADD_DOMAIN_PASS=yes
    - NUO_START_AGENT=yes

matrix:
  include:
    - mono: latest
      script:
        - xbuild /p:TargetFrameworkProfile="" /p:Configuration=Release NuoDb.Data.Client.3.5/Mono.NuoDb.Data.Client_3.5.csproj
        - xbuild /p:TargetFrameworkProfile="" /p:Configuration=Release NuoDb.Data.Client/Mono.NuoDb.Data.Client_4.0.csproj
        - sudo gacutil -i NuoDb.Data.Client/bin/Release/NuoDb.Data.Client.dll
        - mkdir -p ConsoleSample/bin/Release
        - cp NuoDb.Data.Client/bin/Release/NuoDb.Data.Client.dll ConsoleSample/bin/Release
        - xbuild /p:TargetFrameworkProfile="" /p:Configuration=Release ConsoleSample/ConsoleSample.csproj
        - ConsoleSample/bin/Release/ConsoleSample.exe test
        - xbuild /p:TargetFrameworkProfile="" /p:Configuration=Release NUnitTestProject/Mono.NUnitTestProject.csproj
        - TZ=America/New_York mono NUnitTestProject/bin/Release/NUnitTestProject.exe
      env:
        matrix:
          - NUO_VERSION=3.2.2.1
          - NUO_VERSION=3.3.0.1

before_install:
  - echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/enabled >/dev/null
  - echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/defrag >/dev/null

  # There's a bug in the Trusty images where this gives a syntax error
  # See https://github.com/travis-ci/travis-ci/issues/8906
  - sudo mv /opt/jdk_switcher/jdk_switcher.sh /tmp

  - wget -q "http://download.nuohub.org/nuodb-ce_${NUO_VERSION}_amd64.deb" --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb

before_script:
  - if [ "$NUO_ADD_DOMAIN_PASS" = yes ]; then printf '\ndomainPassword = bird\n' | sudo tee -a "$NUODB_HOME"/etc/default.properties >/dev/null; fi
  - if [ "$NUO_START_AGENT" = yes ]; then sudo service nuoagent start; fi
  - $NUODB_HOME/bin/nuodbmgr --broker localhost --password bird --command "start process sm host localhost database test archive /var/tmp/nuodb initialize true"
  - sleep 5
  - $NUODB_HOME/bin/nuodbmgr --broker localhost --password bird --command "start process te host localhost database test options '--dba-user dba --dba-password goalie'"
  - sleep 5

